package traversal;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

public class Occurrance {
	static int count;

	public static void main(String[] args) {
		List<String> ls = new ArrayList<String>();
		ls.add("aa");
		ls.add("aa");
		ls.add("bb");
		ls.add("cc");
		ls.add("dd");
		ls.add("ee");
		ls.add("ee");
		ls.add("aa");
		ls.add("aa");
		ls.add("aa");
		ls.add("aa");
		ls.add("bb");
		ls.add("cc");
		ls.add("dd");
		ls.add("ee");
		ls.add("ee");
		ls.add("aa");
		ls.add("aa");
		ls.add("aa");
		ls.add("aa");
		ls.add("bb");
		ls.add("cc");
		ls.add("dd");
		ls.add("ee");
		ls.add("ee");
		ls.add("aa");
		ls.add("aa");
		ls.add("aa");
		ls.add("aa");
		ls.add("bb");
		ls.add("cc");
		ls.add("dd");
		ls.add("ee");
		ls.add("ee");
		ls.add("aa");
		ls.add("aa");
		ls.add("aa");
		ls.add("aa");
		ls.add("bb");
		ls.add("cc");
		ls.add("dd");
		ls.add("ee");
		ls.add("ee");
		ls.add("aa");
		ls.add("aa");
		ls.add("aa");
		ls.add("aa");
		ls.add("bb");
		ls.add("cc");
		ls.add("dd");
		ls.add("ee");
		ls.add("ee");
		ls.add("aa");
		ls.add("aa");
		ls.add("aa");
		ls.add("aa");
		ls.add("bb");
		ls.add("cc");
		ls.add("dd");
		ls.add("ee");
		ls.add("ee");
		ls.add("aa");
		ls.add("aa");
		ls.add("aa");
		ls.add("aa");
		ls.add("bb");
		ls.add("cc");
		ls.add("dd");
		ls.add("ee");
		ls.add("ee");
		ls.add("aa");
		ls.add("aa");
		ls.add("aa");
		ls.add("aa");
		ls.add("bb");
		ls.add("cc");
		ls.add("dd");
		ls.add("ee");
		ls.add("ee");
		ls.add("aa");
		ls.add("aa");
		ls.add("aa");
		ls.add("aa");
		ls.add("bb");
		ls.add("cc");
		ls.add("dd");
		ls.add("ee");
		ls.add("ee");
		ls.add("aa");
		ls.add("aa");
		ls.add("aa");
		ls.add("aa");
		ls.add("bb");
		ls.add("cc");
		ls.add("dd");
		ls.add("ee");
		ls.add("ee");
		ls.add("aa");
		ls.add("aa");
		ls.add("aa");
		ls.add("aa");
		ls.add("bb");
		ls.add("cc");
		ls.add("dd");
		ls.add("ee");
		ls.add("ee");
		ls.add("aa");
		ls.add("aa");
		ls.add("aa");
		ls.add("aa");
		ls.add("bb");
		ls.add("cc");
		ls.add("dd");
		ls.add("ee");
		ls.add("ee");
		ls.add("aa");
		ls.add("aa");
		ls.add("aa");
		ls.add("aa");
		ls.add("bb");
		ls.add("cc");
		ls.add("dd");
		ls.add("ee");
		ls.add("ee");
		ls.add("aa");
		ls.add("aa");
		ls.add("aa");
		ls.add("aa");
		ls.add("bb");
		ls.add("cc");
		ls.add("dd");
		ls.add("ee");
		ls.add("ee");
		ls.add("aa");
		ls.add("aa");

		Iterator<String> i = ls.iterator();
		while (i.hasNext()) {
			Object a = i.next();
			System.out.println(a);
		}

	}
}
